Cart
eakansh125/Fleetbag pull request #4
Opened 2022-02-16 14:54 UTC by eakansh125

2022-02-16 15:17 UTC, sri-rishi requested changes
![image](https://user-images.githubusercontent.com/72429483/154295477-e81fd668-b264-4d0b-8c2f-499cb08f6696.png)
 
UI is not responsive

2022-02-16 15:21 UTC, sri-rishi reviewed
Just a suggestion next time reduce class name size like image can be img

2022-02-17 11:18 UTC, eakansh125 commented
> ![image](https://user-images.githubusercontent.com/72429483/154295477-e81fd668-b264-4d0b-8c2f-499cb08f6696.png)
> 
> UI is not responsive

I will be making it responsive i the future, thank you

2022-02-21 06:22 UTC, malaykhakhar approved these changes
The code looks good. No suggestions as of now.
UI also looks good with minimalistic design.
You can merge it.

2022-02-21 06:23 UTC, manish-GH approved these changes
Both the code and the UI look good. Remove the unnecessary spacings and replace px with rem wherever possible. Then you are good to merge

2022-02-21 06:23 UTC, manish-GH commented on style.css
>      height: 320px;
use rem here

2022-02-21 06:23 UTC, manish-GH commented on style.css
>      width: 300px;
use rem

2022-02-21 06:25 UTC, pradipgharge approved these changes
A little suggestion on the UI, your primary and secondary buttons look the same on the card. Add some distinction (like a background color) to differentiate b/w both

2022-02-21 06:25 UTC, pradipgharge commented on screens/cart.html
> +
Remove extra spacing here.

2022-02-21 06:25 UTC, pradipgharge commented on style.css
>      width: 300px;
use rems

2022-02-21 06:29 UTC, eakansh125 commented
> Both the code and the UI look good. Remove the unnecessary spacings and replace px with rem wherever possible. Then you are good to merge

Changing px to rems wherever possible

2022-02-21 06:30 UTC, eakansh125 commented
> A little suggestion on the UI, your primary and secondary buttons look the same on the card. Add some distinction (like a background color) to differentiate b/w both

Will surely take care of that in future. Removing extra spaces for now.

2022-02-21 06:40 UTC, merged