Product
eakansh125/Fleetbag pull request #6
Opened 2022-02-19 05:47 UTC by eakansh125

2022-02-19 06:12 UTC, sri-rishi requested changes
![image](https://user-images.githubusercontent.com/72429483/154788831-b62c979e-c087-4861-89e4-2bb737eb1f5d.png)

fix positioning of badge, they are looking separate from icons

2022-02-19 06:22 UTC, eakansh125 commented
> ![image](https://user-images.githubusercontent.com/72429483/154788831-b62c979e-c087-4861-89e4-2bb737eb1f5d.png)
> 
> fix positioning of badge, they are looking separate from icons

They have fixed position, looks a little away because of the cart icon. If I change the icon to something that has a border, you can observe the difference.

2022-02-19 06:26 UTC, Sahil25061999 approved these changes
Looks good just remove the comments if not necessary

2022-02-19 06:34 UTC, eakansh125 commented
> Looks good just remove the comments if not necessary

sure

2022-02-19 06:42 UTC, eakansh125 commented
Fixed badge styling and removed comments

2022-02-19 06:43 UTC, sri-rishi approved these changes

2022-02-19 06:43 UTC, sri-rishi commented on screens/cart.html
> +
remove extra spacing

2022-02-19 06:43 UTC, sri-rishi commented on screens/login.html
> +                        <span class="badge-span">8</span></a>
give alt attribute for img tags

2022-02-19 06:43 UTC, sri-rishi commented on screens/product.css
> +    /* border: 1px solid var(--secondary-grey); */
remove comments

2022-02-19 06:43 UTC, sri-rishi commented on style.css
> +    width: 250px;
use rems instead of px

2022-02-21 07:01 UTC, eakansh125 commented on screens/cart.html
> +
done

2022-02-21 07:01 UTC, eakansh125 commented on style.css
> +    width: 250px;
done

2022-02-21 07:08 UTC, merged